//#ENJOY BROðŸ˜
const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "";
global.video = "";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "Kermd237@gmail.com";
global.location = "Douala, Cameroun";
global.mongodb = process.env.MONGODB_URI || "";
global.allowJids = process.env.ALLOW_JID || "null";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Africa/Douala";
global.github = process.env.GITHUB || "https://github.com/Kgtech-cmr/KERM_MD-V2";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029Vafn6hc7DAX3fzsKtn45";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029Vafn6hc7DAX3fzsKtn45";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/40ffc2a288542560c887c.jpg";
global.devs = "https://wa.me/237650564445 , https://wa.me/237656520674";
global.sudo = process.env.SUDO || "237650564445";
global.owner = process.env.OWNER_NUMBER || "237656520674";
global.style = process.env.STYLE || "3";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "false";
global.userImages = process.env.USER_IMAGES || "https://telegra.ph/file/40ffc2a288542560c887c.jpg";
global.waPresence = process.env.WAPRESENCE || "available";
global.readcmds = process.env.READ_COMMAND || "true";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "false";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://kerm-session-39mi.onrender.com/wasiqr";

global.SESSION_ID =
  process.env.SESSION_ID ||
  "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUE5MGJXZ2w1UnVicE0yOWFncFBpTk9OTC9yYmNKRko1L2lCWng0MEUyWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK245VEZBRUF6Zkh1RkRTTG1UUVlJbFhkUjZ3M2l0KzczYk9FemVGZFpGMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzR0p5YVJyWEt0ZnluWmVRQ1dXQTlwNU1PZ0o4UEQwOU8vaGZBdmt2RjE0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGYkY2c1dTYnR6d2dQZEdUSGpKcFMrdWk4REdPZkRpNFZJNzlaK01abHpnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNFdGk2eFpqeVZKZ2EycHZ0c2hNRkNtQUhFVm9DVnY4L1hjU1MrS1IzR0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik14MzNiWVczcnBPcndFRXZBaWU5aGFtbFZwMjE1L2dNV0lDMWtwN3lUMnc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUhhV2h2UjMwTlZVV0JzUFpzd3pwencyMWJGOEZWTC9NUVFudlgxOVBHcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQU4xeXpNYitWSHNVZ1owZnBMSTc5S0F0dzFPaGVhcVFhUmxTUHVyc3NBOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJLNzltcDZCL2l3QmFDbGtXcmVxajZtWnFUTWpnOHJiVStiTDdYSDB4Y2dTSEh2R2x3OXh6YnVLOVd3ZkN5cm9SZVYvVE5NRGEvUVVCZVdpRzI3ZGhBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTIsImFkdlNlY3JldEtleSI6Ii9saFFmRzZQUzhiNkZNLzhVeDJ3Q2pzNG10R1dTcG9HbyswT1J5U2R3Yms9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjM3Njk3NTc1NDc1QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjA0M0Y1Q0E3OTlBRTJENTc1NzNCODNCNjlGREFDM0U3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjM3NDg4MzB9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzNzY5NzU3NTQ3NUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJCMjZDQTVGRjJFMUNFMjQ1QjgyNDNENjhFQTk0MkY2MyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIzNzQ4ODMyfV0sIm5leHRQcmVLZXlJZCI6NjEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo2MSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJ2NGh1elYtUlR6U3NEOHZTYmtRRUR3IiwicGhvbmVJZCI6ImQ5ODkyNzNkLTNmNDItNDNkZi1iN2Y4LTJkMzA2ZjM2MzdhYSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtUExZQVJCN1lCMHVlTTdham9KemJaZE52bTQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNHYrcmFMQndISHlRNExqc0t2ZUlxNnd3MThFPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlJINFIzWTJWIiwibWUiOnsiaWQiOiIyMzc2OTc1NzU0NzU6OEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJNcnMgUmlzYm8g8J+YjiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTjIwN0JJUXphUDV0UVlZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUFNDV3ZLdng2bkFpSGFZTVJHRFFMUGt5T1BWcktHZUpGaUJXalBZUW13RT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiNzQzMXJhajNROVZrY01qWDVqd0lIazF5ZHV2RWtkNXRjVVhSVFBCd3lwZkoxVkdYbjIrQTcyc3JDMDIzZmx3c09DRjh2am5jNTVnS1g3RjA2MnMwREE9PSIsImRldmljZVNpZ25hdHVyZSI6IitFaHVROW1wSVZSS2p2OFQwOU5sV29mKzNJb0wrNkd4dXFibTJaYUkrZVpmR2wxcWNrZTJ1aXNOYnJ0SE1xOHFkZEhaUGNHZUM4VFFwUVUzcmJaWmpnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM3Njk3NTc1NDc1OjhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVDBnbHJ5cjhlcHdJaDJtREVSZzBDejVNamoxYXlobmlSWWdWb3oyRUpzQiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMzc0ODgyNywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFHcTgifQ=="
module.exports = {
  menu: process.env.MENU || "1",
  HANDLERS: process.env.PREFIX || "#",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.0.0",
  caption: process.env.CAPTION || "`BRAND PRODUCT OF â˜žâŒœ KG TECHâŒâ˜œ`",
  author: process.env.PACK_AUTHER || "KG TECH",
  packname: process.env.PACK_NAME || "Kerm-MD-V2",
  botname: process.env.BOT_NAME || "*Mr_Risbo*",
  ownername: process.env.OWNER_NAME || "Mr_noble",
  errorChat: process.env.ERROR_CHAT || "",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "tCxobE1FqJgfbDZgsYQNHBFB",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "",
  antilink_values: process.env.ANTILINK_VALUES || "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "...d336",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "private",
  LANG: (process.env.THEME || "Kerm-md-v2").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
